### ISSUE TITLE
Record getting hard deleted instead of soft delete

### ISSUE THREAD

**Issue by sourjya** [evilbloodydemon/cakephp-softdeletable2#1]
Hello,
   I tried this code and have set the following in one of my models (Content):
<code>    var $actAs = array(
    'SoftDeletable' => array(
        'field' => 'deleted',
        'field_date' => null,
        'find' => true,
        'status' => 'draft',
    ),
    );
</code>

However when I call $this->Content->delete() to remove a record, instead of the 'deleted' field being set to 0, the record gets completely removed from the database. 

Are any additions / alterations to the code necessary apart from including this module as a behavior? My tables contain the 'deleted' field wherever necessary.

Thanks,
Sourjya

**Comment by evilbloodydemon** [comment]
i suppose that is because of misspelling - $actAs instead of $actsAs. check this, if issue remains, reopen ticket

**Comment by sourjya** [comment]
Yup.. that was it. Silly me :D Thanks for pointing it out.

One question though: Upon setting deleted = 1, the routine returns false. So I cannot check if the softdelete was successful in the conventional sense, i.e.
<code>if( $this->Model->delete() ) { ... }</code>
I have to invert the result and check for it here. This may give rise to confusion in the code, as there are models that implement soft delete and there are models that don't. 
Is there a better way to do it?

Secondly, what is the utility of field_date field? The modified field gets updated anyway and hence a combination of <code>deleted = 1</code> and <code>modified</code> should give one the timestamp of deletion. What are your views on this? Redundant or not? Thanks.

**Comment by evilbloodydemon** [comment]
A1: behaviors cannot return value to userland, if behavior returns false then cake stops further execution of delete method, else it continues and record gets hard-deleted 
A2: there are many ways to change 'modified' field after soft-delete, so it's better to have separate field
